apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-inference-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/llm-gitops.git
    targetRevision: HEAD
    path: .
    directory:
      include: "namespaces/llm-dev.yaml,models/bert-inference-dev.yaml,deployments/bert-inference-service-dev.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: llm-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true