version: '3.8'

services:
  llm-inference:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MODEL_NAME=prajjwal1/bert-tiny  # Default small model for demo
      - DEVICE=cpu                      # Change to cuda for GPU support
      - WORKERS=1                       # Increase for more concurrent requests
      - NUM_LABELS=2                    # Default for binary classification
    volumes:
      # Optional: Mount a local model directory to avoid downloading 
      # - ./my-model:/app/model
      
      # Cache directory for downloaded models
      - huggingface-cache:/app/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

volumes:
  huggingface-cache: