apiVersion: v2
name: argocd
description: A Helm chart for ArgoCD
type: application
version: 0.1.0
appVersion: "v2.14.2"
dependencies:
  - name: argo-cd
    version: 7.8.5
    repository: https://argoproj.github.io/argo-helm
